### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by omoferacho** [ghd-trainingfeb24/captionthis-ghd-p1#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by omoferacho** [comment]
Good Morning

**Comment by insanitysauce** [comment]
Hi Ade!

**Comment by cnfruge** [comment]
I want to join

**Comment by Darrell-Lee** [comment]
Aqui Estoy

**Comment by toddpick** [comment]
Hello World

**Comment by fieldingb** [comment]
GOOD MORNING!!!

**Comment by jimbyer** [comment]
Please add me as a Collaborator.

**Comment by AzureNado** [comment]
howdy

**Comment by davidrueckert** [comment]
Hello

**Comment by nickscape** [comment]
Buenos Dias!

**Comment by utahfunk** [comment]
Commenting

**Comment by debradh2os** [comment]
Hi!

**Comment by forbushbl** [comment]
Thanks for the training!

**Comment by tbpetru** [comment]
Test for echo

**Comment by slcardinal** [comment]
Hello!!

**Comment by tlmaravilla** [comment]
Hi!

**Comment by Samurack** [comment]
print("comment")

**Comment by michaelwreeves** [comment]
Here

**Comment by msterlingjones** [comment]
here

**Comment by jimbyer** [comment]
Please add me as a Collaborator.

**Comment by Darrell-Lee** [comment]
I tried
